language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381903-3_Stetsenko__lab_7
  - make -j
  - ./test/MP2_TESTS
notifications:
  email: false
